import { CodeReviewResult, CommunicationReviewResult } from "../services/scoring.service";

/**
 * Scripted example sessions so the app is demoable without a live recording
 * or an Anthropic API key. These are NOT generated by calling Claude — the
 * scores below are hand-written to look like plausible Claude output and are
 * loaded verbatim by the seed script. Real sessions always get their scores
 * from the two live prompts in backend/prompts/.
 */
export type SampleSession = {
  problemSlug: string;
  language: "javascript" | "python" | "java";
  code: string;
  transcript: string;
  durationSec: number;
  codeReview: CodeReviewResult;
  communicationReview: CommunicationReviewResult;
};

export const SAMPLE_SESSIONS: SampleSession[] = [
  // Flagship example: strong code, weak explanation — the core value prop.
  {
    problemSlug: "two-sum",
    language: "javascript",
    code: `function twoSum(nums, target) {
  const seen = new Map();
  for (let i = 0; i < nums.length; i++) {
    const complement = target - nums[i];
    if (seen.has(complement)) return [seen.get(complement), i];
    seen.set(nums[i], i);
  }
  return [];
}`,
    transcript:
      "So, um, basically I just, like, go through the array and, um, use a map thing to keep track of numbers I've seen, and if the difference is already there I just return it. So yeah, that's kind of it I guess.",
    durationSec: 24,
    codeReview: {
      overall: 9,
      correctness: 9,
      correctness_rationale:
        "The hash map approach correctly tracks each visited number's index and checks for the complement before inserting, so it returns the right pair for both example inputs and handles arbitrary order correctly.",
      time_complexity: "O(n)",
      space_complexity: "O(n)",
      complexity_rationale:
        "Single pass over the array with constant-time map lookups gives O(n) time; the map can hold up to n entries, giving O(n) space.",
      edge_case_coverage: 8,
      edge_cases_missed: ["No explicit handling if no solution exists — falls through to an empty array rather than throwing or signaling clearly."],
      code_quality: 9,
      code_quality_notes: "Clean, idiomatic, well-named variables. Minor: could early-return a clearer error for the no-solution case.",
      summary:
        "Your solution correctly uses a hash map for an optimal O(n) time, O(n) space approach — clean and idiomatic code.",
    },
    communicationReview: {
      overall: 4,
      structure: 2,
      structure_feedback:
        "There's no upfront statement of approach — you launch straight into implementation details without ever naming the technique (a hash map for single-pass lookup).",
      clarity: 4,
      clarity_feedback:
        "\"A map thing\" and \"the difference\" are vague. An interviewer would want you to name the data structure and the exact value you're computing (the complement).",
      confidence: 4,
      confidence_feedback:
        "High filler density (measured: 6 filler words in a 24-second answer) and hedging language like \"I guess\" undercut an otherwise correct answer.",
      completeness: 3,
      completeness_feedback:
        "No mention of time or space complexity, and no edge cases discussed out loud, even though your code handles this well.",
      pacing: 6,
      pacing_feedback: "Pace itself is fine, but the answer is too short to demonstrate real depth.",
      summary:
        "You never stated your approach up front, and you didn't mention time or space complexity or any edge cases out loud — even though your code correctly uses a hash map.",
      tips: [
        {
          tip: "Open with the technique by name before describing steps: \"I'll use a hash map to do this in one pass.\"",
          quote: "basically I just, like, go through the array",
        },
        {
          tip: "State the Big-O explicitly — you clearly know it's a single pass, so say \"O(n) time, O(n) space\" out loud.",
          quote: "So yeah, that's kind of it I guess.",
        },
        {
          tip: "Cut hedge words like \"I guess\" and \"kind of\" — they make a correct answer sound unsure.",
          quote: "that's kind of it I guess",
        },
      ],
    },
  },

  // Flip side: mediocre code, strong explanation.
  {
    problemSlug: "climbing-stairs",
    language: "javascript",
    code: `function climbStairs(n) {
  if (n <= 2) return n;
  return climbStairs(n - 1) + climbStairs(n - 2);
}`,
    transcript:
      "My approach here is to use recursion: the number of ways to reach step n is the sum of the ways to reach step n minus one and step n minus two, since from either of those steps you can take one final step. I coded that directly as a recursive function with a base case for n less than or equal to two. The trade-off is that this recursive version recomputes the same subproblems many times, so it's actually exponential time, order two to the n. In a real interview I'd follow up by adding memoization or switching to an iterative bottom-up approach to bring that down to linear time and constant space.",
    durationSec: 42,
    codeReview: {
      overall: 6,
      correctness: 9,
      correctness_rationale:
        "The recurrence relation is correct and the base case for n <= 2 handles both n=1 and n=2 properly, matching the examples.",
      time_complexity: "O(2^n)",
      space_complexity: "O(n)",
      complexity_rationale:
        "Each call branches into two more calls with no memoization, giving exponential time; the recursion depth is n, giving O(n) stack space.",
      edge_case_coverage: 8,
      edge_cases_missed: [],
      code_quality: 6,
      code_quality_notes:
        "Correct and concise, but a naive recursive solution without memoization would time out for larger n — a real interview submission should include the DP version.",
      summary:
        "Your recursion is correct but exponential — this works for small n but a bottom-up or memoized version is expected for full marks.",
    },
    communicationReview: {
      overall: 9,
      structure: 9,
      structure_feedback:
        "Textbook structure: you stated the recurrence and approach before describing the code at all, then closed with complexity and next steps.",
      clarity: 9,
      clarity_feedback:
        "Explained the recurrence in plain language anyone could follow, without leaning on jargon.",
      confidence: 8,
      confidence_feedback: "Fluent delivery with essentially no filler words measured, and no hedging language.",
      completeness: 10,
      completeness_feedback:
        "Explicitly called out the time complexity, the space complexity, AND the optimization trade-off unprompted — exactly what a strong candidate does.",
      pacing: 8,
      pacing_feedback: "Comfortable, unhurried pace matched to a 42-second answer of this length.",
      summary:
        "You opened with the recurrence, correctly flagged the exponential blow-up, and proactively named the fix — this is close to how a strong candidate should sound, even though the code itself is unoptimized.",
      tips: [
        {
          tip: "Since you already spotted the exponential blow-up, mention it before writing the naive version rather than after, so the interviewer knows it's a deliberate first pass.",
          quote: "it's actually exponential time, order two to the n",
        },
        {
          tip: "Name the exact fix (\"a bottom-up array\" or \"a memo object keyed by n\") rather than \"memoization\" generically.",
          quote: "adding memoization or switching to an iterative bottom-up approach",
        },
      ],
    },
  },

  // Both strong.
  {
    problemSlug: "number-of-islands",
    language: "javascript",
    code: `function numIslands(grid) {
  if (!grid || grid.length === 0) return 0;
  const rows = grid.length, cols = grid[0].length;
  let count = 0;

  function dfs(r, c) {
    if (r < 0 || c < 0 || r >= rows || c >= cols || grid[r][c] === '0') return;
    grid[r][c] = '0';
    dfs(r + 1, c);
    dfs(r - 1, c);
    dfs(r, c + 1);
    dfs(r, c - 1);
  }

  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      if (grid[r][c] === '1') {
        count++;
        dfs(r, c);
      }
    }
  }
  return count;
}`,
    transcript:
      "I'll treat the grid as a graph where each land cell is a node connected to its up, down, left, and right neighbors. My approach is to scan every cell, and whenever I find an unvisited land cell, that's a new island, so I increment my count and then run a depth-first search to sink every connected land cell by marking it as water so I don't count it again. Time complexity is order rows times columns since every cell is visited a constant number of times, and space complexity is order rows times columns in the worst case for the recursion stack if the whole grid is one island. One edge case I thought about is an empty grid, so I return zero immediately if the grid has no rows.",
    durationSec: 45,
    codeReview: {
      overall: 9,
      correctness: 9,
      correctness_rationale:
        "The flood-fill DFS correctly sinks every connected land cell before continuing the scan, so each island is counted exactly once across the provided example.",
      time_complexity: "O(rows * cols)",
      space_complexity: "O(rows * cols)",
      complexity_rationale:
        "Every cell is visited a constant number of times overall; the recursion stack can grow to the size of the grid in the worst case (one giant island).",
      edge_case_coverage: 9,
      edge_cases_missed: [],
      code_quality: 9,
      code_quality_notes: "Clear separation between the scan loop and the DFS helper, with a sensible empty-grid guard.",
      summary: "A clean, correct flood-fill solution with the expected time and space complexity and a handled empty-grid edge case.",
    },
    communicationReview: {
      overall: 9,
      structure: 9,
      structure_feedback: "Approach (grid-as-graph, scan + sink) stated fully before any implementation detail.",
      clarity: 9,
      clarity_feedback: "The 'sink visited land so it's not recounted' framing is precise and easy to follow.",
      confidence: 9,
      confidence_feedback: "Fluent, minimal filler words measured (3, all legitimate transitions rather than disfluencies), no hedging.",
      completeness: 9,
      completeness_feedback: "Covered time complexity, space complexity, and an edge case (empty grid) without being asked.",
      pacing: 8,
      pacing_feedback: "Well-paced for a 45-second answer covering this much ground.",
      summary: "A model answer: approach first, complexity and edge cases stated proactively, and it matches what the code actually does.",
      tips: [
        {
          tip: "You could briefly mention the alternative of BFS with a queue to show you know it's not the only valid traversal.",
          quote: "run a depth-first search to sink every connected land cell",
        },
      ],
    },
  },

  // Both middling/weak.
  {
    problemSlug: "best-time-to-buy-sell-stock",
    language: "javascript",
    code: `function maxProfit(prices) {
  let max = 0;
  for (let i = 0; i < prices.length; i++) {
    for (let j = i + 1; j < prices.length; j++) {
      if (prices[j] - prices[i] > max) {
        max = prices[j] - prices[i];
      }
    }
  }
  return max;
}`,
    transcript:
      "Um, okay so, like, I just check, um, every pair of days and see, like, which one gives the the biggest difference, um, and then I just return that, so, um yeah that's basically it, I think it works.",
    durationSec: 22,
    codeReview: {
      overall: 6,
      correctness: 8,
      correctness_rationale:
        "The brute-force pairwise comparison correctly finds the maximum profit for both example inputs, including returning 0 when prices only decrease.",
      time_complexity: "O(n^2)",
      space_complexity: "O(1)",
      complexity_rationale: "Nested loop over all pairs of days with no extra data structures.",
      edge_case_coverage: 7,
      edge_cases_missed: ["Doesn't short-circuit or note that a single-pass O(n) solution exists, which matters for the given constraint of up to 10^5 prices."],
      code_quality: 6,
      code_quality_notes: "Correct but the O(n^2) approach won't scale to the stated constraints; a single min-so-far pass is expected.",
      summary: "Correct, but the O(n^2) brute force is too slow for the problem's constraints — a single-pass O(n) solution is expected here.",
    },
    communicationReview: {
      overall: 4,
      structure: 3,
      structure_feedback: "No approach stated up front — jumps directly into describing the double loop.",
      clarity: 4,
      clarity_feedback: "\"Every pair of days\" is fine, but there's no mention of what data structure or technique is being used, or why.",
      confidence: 3,
      confidence_feedback: "Very high filler density for the length of the answer (measured: 9 filler words in 22 seconds), plus a trailing hedge (\"I think it works\").",
      completeness: 2,
      completeness_feedback: "No time or space complexity mentioned at all, and no acknowledgment that a faster approach exists.",
      pacing: 5,
      pacing_feedback: "Short and rushed relative to the ground that should be covered for this problem.",
      summary: "The explanation doesn't mention complexity at all and is heavy on filler words — an interviewer would push hard on 'can you do better than checking every pair?' here.",
      tips: [
        {
          tip: "State the complexity of your own approach, even when it's not optimal — silence on this reads worse than naming it and then proposing the fix.",
          quote: "that's basically it, I think it works",
        },
        {
          tip: "Proactively flag the better approach: \"this is O(n squared); a single pass tracking the minimum price so far would get this to O(n).\"",
          quote: "I just check, um, every pair of days",
        },
        {
          tip: "Cut the filler words — try pausing silently instead of saying \"um\" between thoughts.",
          quote: "Um, okay so, like, I just check, um, every pair of days",
        },
      ],
    },
  },
];
